### ISSUE TITLE
Bug | Restrict Public Access in several S3 Buckets Replicas cross-org

### ISSUE THREAD

**Issue by marianod92** [binbashar/terraform-aws-tfstate-backend#18]
## What?

- ⚠️ Restrict public access in several S3 Buckets Replicas cross-org which are miss-configured
- ❗ Whenever possible the fix must be included in the instantiated modules, such as:
  - https://github.com/binbashar/terraform-aws-tfstate-backend
## Why?

![image](https://user-images.githubusercontent.com/35702375/183219513-836c21dd-1d14-4487-b983-1972b9818ff6.png)

## How?

- Adds public access configuration block with the same input variables as the main bucket (perhaps enforce by default in true the variables for public access restrictions). This configuration should be in this [bucket_replication.tf](https://github.com/binbashar/terraform-aws-tfstate-backend/blob/f8dcfaed7cd4707995c1ae5cde51dcc2ef5b7bfc/bucket_replication.tf)

```
resource "aws_s3_bucket_public_access_block" "default" {
  provider                = aws.primary
  bucket                  = aws_s3_bucket.default.id
  block_public_acls       = var.block_public_acls
  ignore_public_acls      = var.ignore_public_acls
  block_public_policy     = var.block_public_policy
  restrict_public_buckets = var.restrict_public_buckets
  depends_on              = [aws_s3_bucket.default]
}
```
This bug was detected in the resolution of [Issue #256.](https://github.com/binbashar/le-tf-infra-aws/issues/256)

**Comment by exequielrafaela** [comment]
@marianod92 this issue was covered at https://github.com/binbashar/terraform-aws-tfstate-backend/pull/19/files# however we still need to update the Ref Arch module to use the latest module version in order to complete fix this. Hope to prioritize this for 2022 Q3 iterations.

CC: @binbashar/leverage-ref-architecture-aws-admin @binbashar/leverage-ref-architecture-aws-dev

**Comment by exequielrafaela** [comment]
https://github.com/binbashar/le-tf-infra-aws/pull/431/files
