### ISSUE TITLE
Support v5 of the AWS provider

### ISSUE THREAD

**Issue by d3adb5** [binbashar/terraform-aws-tfstate-backend#29]
## Describe the Feature

Version 5 of the officlal AWS provider for Terraform was released back in May of this year (2023). Since then, there have been no v4 releases (latest one, v4.67.0, was in May 11), though I was unable to find official announcements or articles backing up the lack of support for v4.

While not overly complex, the changes required to upgrade this module from v4 to v5 should be looked over carefully. [This part of the documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-5-upgrade) explains what to expect when upgrading.

## Expected Behavior

Modules using version 5 of the AWS provider should be able to invoke this module without generating any warnings, regressions, or unexpected behavior.

## Use Case

Anyone writing Terraform modules / configuration around version 5 of the AWS provider and also invoking this module will require support.

## Alternatives Considered

Continuing to support this module built around v4 of the provider means passing on bug fixes and improvements that come with version 5 of the AWS provider.

**Comment by martingaleano** [comment]
Closed - PR https://github.com/binbashar/terraform-aws-tfstate-backend/pull/30
