### ISSUE TITLE
Error when replication bucket is disabled

### ISSUE THREAD

**Issue by mpagnucco** [binbashar/terraform-aws-tfstate-backend#6]
Issue is that even wih bucket being conditional the provider for it is not (not possible with current terraform), hence it fails to run when replication bucket is disabled.

```
Error: Invalid AWS Region: 

  on .terraform/modules/security_terraform_backend/bucket_replication.tf line 1, in provider "aws":
   1: provider "aws" {

```

**Comment by diego-ojeda-binbash** [comment]
@exequielrafaela @mpagnucco I just pushed a fix for this: https://github.com/binbashar/terraform-aws-tfstate-backend/pull/8
